baseURL = 'https://bernie6401.github.io/'
languageCode = 'en-us'
title = 'SBK Site'
theme = 'hugo-book'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1

[params]
  BookTheme = 'auto'
  BookToC = true
  BookLogo = 'logo.jpg'
  BookFavicon = "favicon.jpg"
  BookRepo = https://github.com/bernie6401/bernie6401.github.io
  BookCommitPath = commit
  BookEditPath = 'edit/main/demo'
  BookDateFormat = "January 2, 2006"